#!/usr/bin/env node
/**
 * sync-env.js
 * Reads ../.env and writes only the NEXT_PUBLIC_* lines into .env.local
 * so Next.js (including Edge Runtime / proxy) can resolve them.
 *
 * This file IS committed to git — it contains zero secrets.
 * .env.local is git-ignored (safe).
 */
const fs = require("fs");
const path = require("path");

const src = path.resolve(__dirname, "../../.env");
const dest = path.resolve(__dirname, "../.env.local");

if (!fs.existsSync(src)) {
  console.error("[sync-env] ERROR: ../.env not found. Create it from .env.example first.");
  process.exit(1);
}

const lines = fs.readFileSync(src, "utf8").split("\n");
const publicLines = lines.filter(
  (l) => l.startsWith("NEXT_PUBLIC_") && l.includes("=")
);

fs.writeFileSync(
  dest,
  `# AUTO-GENERATED by scripts/sync-env.js — do not edit manually.\n# Source: ../.env (git-ignored)\n\n${publicLines.join("\n")}\n`
);

console.log(`[sync-env] ✓ Wrote ${publicLines.length} NEXT_PUBLIC_* vars to .env.local`);
